package SkateboardLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ColorReducedEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ColorReducedEnum() {
    super(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737bbac9cL, "ColorReducedEnum", "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846981276");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_black_0 = new EnumerationDescriptor.MemberDescriptor("black", "black", 0x6445109737bbac9dL, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846981277");
  private final EnumerationDescriptor.MemberDescriptor myMember_white_0 = new EnumerationDescriptor.MemberDescriptor("white", "white", 0x6445109737bbae0aL, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846981642");
  private final EnumerationDescriptor.MemberDescriptor myMember_silver_0 = new EnumerationDescriptor.MemberDescriptor("silver", "silver", 0x6445109737bbae41L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846981697");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737bbac9cL, 0x6445109737bbac9dL, 0x6445109737bbae0aL, 0x6445109737bbae41L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_black_0, myMember_white_0, myMember_silver_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "black":
        return myMember_black_0;
      case "white":
        return myMember_white_0;
      case "silver":
        return myMember_silver_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
