package SkateboardLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_DecorationShapeEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_DecorationShapeEnum() {
    super(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737bc091fL, "DecorationShapeEnum", "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418847004959");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_circle_0 = new EnumerationDescriptor.MemberDescriptor("circle", "circle", 0x6445109737bc0920L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418847004960");
  private final EnumerationDescriptor.MemberDescriptor myMember_square_0 = new EnumerationDescriptor.MemberDescriptor("square", "square", 0x6445109737bc0a3fL, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418847005247");
  private final EnumerationDescriptor.MemberDescriptor myMember_triangle_0 = new EnumerationDescriptor.MemberDescriptor("triangle", "triangle", 0x6445109737bc0a90L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418847005328");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737bc091fL, 0x6445109737bc0920L, 0x6445109737bc0a3fL, 0x6445109737bc0a90L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_circle_0, myMember_square_0, myMember_triangle_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "circle":
        return myMember_circle_0;
      case "square":
        return myMember_square_0;
      case "triangle":
        return myMember_triangle_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
