package SkateboardLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_BodyEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_BodyEnum() {
    super(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737b99affL, "BodyEnum", "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846845695");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_standard_0 = new EnumerationDescriptor.MemberDescriptor("standard", "standard", 0x6445109737b99b00L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846845696");
  private final EnumerationDescriptor.MemberDescriptor myMember_carver_0 = new EnumerationDescriptor.MemberDescriptor("carver", "carver", 0x6445109737b99b1bL, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846845723");
  private final EnumerationDescriptor.MemberDescriptor myMember_downhill_0 = new EnumerationDescriptor.MemberDescriptor("downhill", "downhill", 0x6445109737b99b1eL, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846845726");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737b99affL, 0x6445109737b99b00L, 0x6445109737b99b1bL, 0x6445109737b99b1eL);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_standard_0, myMember_carver_0, myMember_downhill_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "standard":
        return myMember_standard_0;
      case "carver":
        return myMember_carver_0;
      case "downhill":
        return myMember_downhill_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
