package SkateboardLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_WheelShapeEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_WheelShapeEnum() {
    super(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737bb5a48L, "WheelShapeEnum", "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846960200");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_cylindrical_0 = new EnumerationDescriptor.MemberDescriptor("cylindrical", "cylindrical", 0x6445109737bb5a49L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846960201");
  private final EnumerationDescriptor.MemberDescriptor myMember_spherical_0 = new EnumerationDescriptor.MemberDescriptor("spherical", "spherical", 0x6445109737bb5b82L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846960514");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737bb5a48L, 0x6445109737bb5a49L, 0x6445109737bb5b82L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_cylindrical_0, myMember_spherical_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "cylindrical":
        return myMember_cylindrical_0;
      case "spherical":
        return myMember_spherical_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
