package SkateboardLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_WidthEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_WidthEnum() {
    super(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737ba4f22L, "WidthEnum", "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846891810");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_medium_0 = new EnumerationDescriptor.MemberDescriptor("medium", "medium", 0x6445109737ba4f23L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846891811");
  private final EnumerationDescriptor.MemberDescriptor myMember_small_0 = new EnumerationDescriptor.MemberDescriptor("small", "small", 0x6445109737ba505dL, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846892125");
  private final EnumerationDescriptor.MemberDescriptor myMember_large_0 = new EnumerationDescriptor.MemberDescriptor("large", "large", 0x6445109737ba5094L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846892180");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737ba4f22L, 0x6445109737ba4f23L, 0x6445109737ba505dL, 0x6445109737ba5094L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_medium_0, myMember_small_0, myMember_large_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "medium":
        return myMember_medium_0;
      case "small":
        return myMember_small_0;
      case "large":
        return myMember_large_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
