package SkateboardLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.EnumerationDescriptorBase;
import jetbrains.mps.smodel.runtime.EnumerationDescriptor;
import jetbrains.mps.lang.smodel.EnumerationLiteralsIndex;
import java.util.List;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.annotations.NotNull;

public class EnumerationDescriptor_ColorEnum extends EnumerationDescriptorBase {

  public EnumerationDescriptor_ColorEnum() {
    super(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737ba9697L, "ColorEnum", "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910103");
  }

  private final EnumerationDescriptor.MemberDescriptor myMember_red_0 = new EnumerationDescriptor.MemberDescriptor("red", "red", 0x6445109737ba9698L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910104");
  private final EnumerationDescriptor.MemberDescriptor myMember_orange_0 = new EnumerationDescriptor.MemberDescriptor("orange", "orange", 0x6445109737ba974fL, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910287");
  private final EnumerationDescriptor.MemberDescriptor myMember_yellow_0 = new EnumerationDescriptor.MemberDescriptor("yellow", "yellow", 0x6445109737ba9786L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910342");
  private final EnumerationDescriptor.MemberDescriptor myMember_green_0 = new EnumerationDescriptor.MemberDescriptor("green", "green", 0x6445109737ba97d8L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910424");
  private final EnumerationDescriptor.MemberDescriptor myMember_blue_0 = new EnumerationDescriptor.MemberDescriptor("blue", "blue", 0x6445109737ba97f7L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910455");
  private final EnumerationDescriptor.MemberDescriptor myMember_purple_0 = new EnumerationDescriptor.MemberDescriptor("purple", "purple", 0x6445109737ba9831L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910513");
  private final EnumerationDescriptor.MemberDescriptor myMember_pink_0 = new EnumerationDescriptor.MemberDescriptor("pink", "pink", 0x6445109737ba986cL, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910572");
  private final EnumerationDescriptor.MemberDescriptor myMember_black_0 = new EnumerationDescriptor.MemberDescriptor("black", "black", 0x6445109737ba98a8L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910632");
  private final EnumerationDescriptor.MemberDescriptor myMember_silver_0 = new EnumerationDescriptor.MemberDescriptor("silver", "silver", 0x6445109737ba98e5L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910693");
  private final EnumerationDescriptor.MemberDescriptor myMember_white_0 = new EnumerationDescriptor.MemberDescriptor("white", "white", 0x6445109737ba9923L, "r:1a9f7ae8-02f9-4e05-b5c0-b834b94e8a1b(SkateboardLanguage.structure)/7225199418846910755");

  private final EnumerationLiteralsIndex myIndex = EnumerationLiteralsIndex.build(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL, 0x6445109737ba9697L, 0x6445109737ba9698L, 0x6445109737ba974fL, 0x6445109737ba9786L, 0x6445109737ba97d8L, 0x6445109737ba97f7L, 0x6445109737ba9831L, 0x6445109737ba986cL, 0x6445109737ba98a8L, 0x6445109737ba98e5L, 0x6445109737ba9923L);
  private final List<EnumerationDescriptor.MemberDescriptor> myMembers = new EnumerationDescriptorBase.MembersList(myIndex, myMember_red_0, myMember_orange_0, myMember_yellow_0, myMember_green_0, myMember_blue_0, myMember_purple_0, myMember_pink_0, myMember_black_0, myMember_silver_0, myMember_white_0);

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getDefault() {
    return null;
  }

  @NotNull
  @Override
  public List<EnumerationDescriptor.MemberDescriptor> getMembers() {
    return myMembers;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(@Nullable String memberName) {
    if (memberName == null) {
      return null;
    }
    switch (memberName) {
      case "red":
        return myMember_red_0;
      case "orange":
        return myMember_orange_0;
      case "yellow":
        return myMember_yellow_0;
      case "green":
        return myMember_green_0;
      case "blue":
        return myMember_blue_0;
      case "purple":
        return myMember_purple_0;
      case "pink":
        return myMember_pink_0;
      case "black":
        return myMember_black_0;
      case "silver":
        return myMember_silver_0;
      case "white":
        return myMember_white_0;
    }
    return null;
  }

  @Nullable
  @Override
  public EnumerationDescriptor.MemberDescriptor getMember(long idValue) {
    int index = myIndex.index(idValue);
    if (index == -1) {
      return null;
    }
    return myMembers.get(index);
  }
}
