package SkateboardLanguage.structure;

/*Generated by MPS */

import jetbrains.mps.lang.smodel.LanguageConceptIndex;
import jetbrains.mps.lang.smodel.LanguageConceptIndexBuilder;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import org.jetbrains.mps.openapi.language.SAbstractConcept;

public final class LanguageConceptSwitch {
  private final LanguageConceptIndex myIndex;
  public static final int Body = 0;
  public static final int BoltsColor = 1;
  public static final int Color = 2;
  public static final int Decoration = 3;
  public static final int DecorationShape = 4;
  public static final int DecorationSize = 5;
  public static final int Foldable = 6;
  public static final int Gridtape = 7;
  public static final int GridtapeColor = 8;
  public static final int GridtapeSize = 9;
  public static final int Length = 10;
  public static final int Rails = 11;
  public static final int RailsSize = 12;
  public static final int Risers = 13;
  public static final int RisersColor = 14;
  public static final int RisersSize = 15;
  public static final int Skateboard = 16;
  public static final int Truck = 17;
  public static final int TruckColor = 18;
  public static final int Wheel = 19;
  public static final int WheelDecoration = 20;
  public static final int WheelShape = 21;
  public static final int WheelSize = 22;
  public static final int Width = 23;

  public LanguageConceptSwitch() {
    LanguageConceptIndexBuilder builder = new LanguageConceptIndexBuilder(0x9dddfad4b7d4b93L, 0x8c0f0c6d986fc2dfL);
    builder.put(0x6445109737b99602L, Body);
    builder.put(0x6445109737bbcdc9L, BoltsColor);
    builder.put(0x6445109737ba948cL, Color);
    builder.put(0x6445109737bbf725L, Decoration);
    builder.put(0x6445109737bc00c7L, DecorationShape);
    builder.put(0x6445109737bcbda0L, DecorationSize);
    builder.put(0x6445109737baadd8L, Foldable);
    builder.put(0x6445109737bcd165L, Gridtape);
    builder.put(0x6445109737bd0a12L, GridtapeColor);
    builder.put(0x6445109737bce58cL, GridtapeSize);
    builder.put(0x6445109737b9e34eL, Length);
    builder.put(0x6445109737bd1b16L, Rails);
    builder.put(0x6445109737bd2d0aL, RailsSize);
    builder.put(0x6445109737bd45e1L, Risers);
    builder.put(0x6445109737bd706cL, RisersColor);
    builder.put(0x6445109737bd5b08L, RisersSize);
    builder.put(0x6445109737b933aaL, Skateboard);
    builder.put(0x6445109737bb902bL, Truck);
    builder.put(0x6445109737bbaf7eL, TruckColor);
    builder.put(0x6445109737bac118L, Wheel);
    builder.put(0x6445109737bb7a3dL, WheelDecoration);
    builder.put(0x6445109737bb523eL, WheelShape);
    builder.put(0x6445109737baca42L, WheelSize);
    builder.put(0x6445109737ba4ce3L, Width);
    myIndex = builder.seal();
  }

  /*package*/ int index(SConceptId cid) {
    return myIndex.index(cid);
  }

  public int index(SAbstractConcept concept) {
    return myIndex.index(concept);
  }
}
